// Generated by CoffeeScript 1.6.2
// ==UserScript==
// @name        Jon's Incredible JIRA Sprint Board Minor Improvements
// @namespace   http://gm.delphae.net/
// @description Add a few improvements to the JIRA sprint board, such as adding a context menu to issues.
// @include     *.atlassian.net/secure/RapidBoard.jspa*
// @grant       GM_addStyle
// @version     4.1
// ==/UserScript==
;
var main, script;

main = function($) {
  var API_URL, bindings, buildMenu, clearImmediate, decorateCard, initIssueCards, initPlanView, isBlocked, setBlocked, setImmediate, _ref;

  API_URL = '/rest/api/2/';
  bindings = {};
  setImmediate = (_ref = window.setImmediate) != null ? _ref : function(func, args) {
    return window.setTimeout(func, 0, args);
  };
  clearImmediate = window.clearTimeout;
  isBlocked = function(link) {
    var _ref1;

    if (link.type.inward === "is blocked by") {
      return (link.outwardIssue == null) && ((_ref1 = link.inwardIssue) != null ? _ref1.fields.status.name : void 0) !== "Done";
    }
  };
  setBlocked = function(card, value) {
    var flag;

    if (value == null) {
      value = true;
    }
    flag = $(card).find('.blocked-flag');
    if (value) {
      return flag.css('display', 'inline-block');
    } else {
      return flag.hide();
    }
  };
  buildMenu = function(id, items) {
    var bindingId, config, elem, ul, _ref1;

    if ((_ref1 = bindings[id]) == null) {
      bindings[id] = {};
    }
    elem = $('<div>').attr({
      'class': 'contextMenu',
      'id': id
    });
    elem.hide();
    ul = $('<ul>');
    for (bindingId in items) {
      config = items[bindingId];
      ul.append($("<li id='" + bindingId + "'>").text(config.name));
      bindings[id][bindingId] = config.callback;
    }
    elem.append(ul);
    return $('body').append(elem);
  };
  decorateCard = function(card, data) {
    var attachmentFlag, blockedFlag, commentFlag, flags, label, link, list, span, _i, _j, _len, _len1, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _results;

    blockedFlag = $('<img>');
    blockedFlag.hide();
    blockedFlag.attr({
      'src': '/images/icons/emoticons/error.gif',
      'alt': ' (Blocked)',
      'title': 'This story is blocked!',
      'class': 'blocked-flag'
    });
    $(card).find('.js-detailview').after(blockedFlag);
    if (data.fields != null) {
      flags = $(card).find('.ghx-flags');
      if ((_ref1 = data.fields.labels) != null ? _ref1.length : void 0) {
        list = $('<div>').attr('class', 'label-list').hide();
        $(card).append(list);
        _ref2 = data.fields.labels;
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          label = _ref2[_i];
          span = $('<span>');
          span.text(label);
          list.append(span);
          if (label.toLowerCase() === 'blocked' && ((_ref3 = data.fields.status) != null ? _ref3.name : void 0) !== 'Done') {
            setBlocked(card);
          }
        }
        list.show();
      }
      if ((_ref4 = data.fields.attachment) != null ? _ref4.length : void 0) {
        attachmentFlag = $('<span>');
        attachmentFlag.addClass('uses-sprite has-attachment');
        flags.append(attachmentFlag);
      }
      if ((_ref5 = data.fields.comment.comments) != null ? _ref5.length : void 0) {
        commentFlag = $('<span>');
        commentFlag.addClass('uses-sprite has-comments');
        flags.append(commentFlag);
      }
      if ((_ref6 = data.fields.issuelinks) != null ? _ref6.length : void 0) {
        _ref7 = data.fields.issuelinks;
        _results = [];
        for (_j = 0, _len1 = _ref7.length; _j < _len1; _j++) {
          link = _ref7[_j];
          if (!(isBlocked(link) && ((_ref8 = data.fields.status) != null ? _ref8.name : void 0) !== 'Done')) {
            continue;
          }
          setBlocked(card);
          break;
        }
        return _results;
      }
    }
  };
  initIssueCards = function() {
    var FIELDS, card, cards, _i, _len, _results;

    FIELDS = ['attachment', 'comment', 'issuelinks', 'labels', 'status'];
    cards = $('#ghx-work .ghx-issue');
    _results = [];
    for (_i = 0, _len = cards.length; _i < _len; _i++) {
      card = cards[_i];
      _results.push((function(card) {
        return setImmediate(function() {
          return $.ajax("" + API_URL + "issue/" + ($(card).data('issueId')) + "?fields=" + (FIELDS.join(',')), {
            dataType: 'json',
            type: 'GET',
            success: function(data) {
              return decorateCard(card, data);
            },
            error: function(xhr, status, error) {
              return console.debug("Error fetching data for issue " + ($(card).data()));
            }
          });
        });
      })(card));
    }
    return _results;
  };
  initPlanView = function() {};
  initIssueCards();
  initPlanView();
  $('#fancybox-outer').on('dblclick', '#fancybox-img', function(e) {
    return window.open($(this).attr('src'));
  });
  $(document).bind("DOMNodeInserted", function(e) {
    var target;

    target = $(e.target);
    if (target.attr('id') === 'js-pool-end') {
      initIssueCards();
    }
    if (target.hasClass('ghx-foot')) {
      return initPlanView();
    }
  });
  setTimeout((function() {
    return $('#ghx-work').on('dblclick', '.ghx-issue', function(e) {
      return $(e.currentTarget).find('.js-detailview')[0].click();
    });
  }), 100);
  return $(document.body).on('click', 'a.external-link', function(e) {
    return $(e.target).attr('target', '_blank');
  });
};

script = document.createElement('script');

script.textContent = "(" + (main.toString()) + ")(window.AJS.$);";

document.body.appendChild(script);

GM_addStyle("    #ghx-work .ghx-issue .label-list span {        background: #b4c8d2;        border: 1px solid #d9e7f3;        border-radius: 0.4em;        margin-right: 0.5em;        padding: 0 0.2em;        position: relative;        top: -1.15em;    }    #ghx-work .ghx-issue .ghx-type {        display: none;    }    #ghx-work .ghx-issue .ghx-flags {        top: 6px;    }    #ghx-work .ghx-issue .ghx-flags span:nth-of-type(2) {        margin-top: 4px;    }    #ghx-work .ghx-issue .ghx-flags span {        display: block;        height: 14px;        margin-bottom: 2px;        vertical-align: middle;        width: 16px;    }    #ghx-work .ghx-issue .ghx-flags .uses-sprite {        background-image: url('https://mobilefun.atlassian.net/s/en_US-seakxi-418945332/6007/29/6.1-rc1/_/download/resources/com.pyxis.greenhopper.jira:gh-rapid-common/images/rapid/ghx-icon-sprite.png');        background-repeat: no-repeat;    }    #ghx-work .ghx-issue .ghx-flags .has-attachment {        background-position: 0 -350px;    }    #ghx-work .ghx-issue .ghx-flags .has-comments {        background-position: 0 -325px;    }    #ghx-work .ghx-issue .blocked-flag {        height: 1em;        left: 0.33em;        position: relative;        top: 0.17em;        width: 1em;    }    #ghx-plan .ghx-issue-compact .ghx-type {        display: none;    }    #ghx-plan .ghx-issue-compact .ghx-flags {        display: none;    }    #ghx-plan .ghx-issue-compact .ghx-issue-fields {        left: -40px;        position: relative;    }");
